export const TOGGLE_PLAY_AUDIO_CALL = 'TOGGLE_PLAY_AUDIO_CALL';
export const SET_KIND_OF_GAME_AUDIO_CALL = 'SET_KIND_OF_GAME_AUDIO_CALL';
export const SET_ROUND_AND_LEVEL_GAME_AUDIO_CALL = 'SET_ROUND_AND_LEVEL_GAME_AUDIO_CALL';
export const SET_GAME_NUMBER_AUDIO_CALL = 'SET_GAME_NUMBER_AUDIO_CALL';
export const SET_RANDOM_GAME_NUMBER_AUDIO_CALL = 'SET_RANDOM_GAME_NUMBER_AUDIO_CALL';
export const SET_QUESTION_NUMBER_AUDIO_CALL = 'SET_QUESTION_NUMBER_AUDIO_CALL';
export const SET_QUESTIONS_AUDIO_CALL = 'SET_QUESTIONS_AUDIO_CALL';
export const SET_STATISTIC_AUDIO_CALL = 'SET_STATISTIC_AUDIO_CALL';
