export const TOGGLE_PLAY_GAME = 'TOGGLE_PLAY_GAME';
export const SET_QUESTIONS_GAME = 'SET_QUESTIONS_GAME';
export const ASK_QUESTION = 'ASK_QUESTION';
export const ANSWER_GAME = 'ANSWER_GAME';
export const SET_STATISTIC_GAME = 'SET_STATISTIC_GAME';
export const SET_GAME_NUMBER = 'SET_GAME_NUMBER';
