export const TOGGLE_PLAY_GAME = 'TOGGLE_PLAY_GAME';
export const GET_DATA_GAME = 'GET_DATA_GAME';
export const SET_DATA_GAME = 'SET_DATA_GAME';
export const SET_QUESTIONS_GAME = 'SET_QUESTIONS_GAME';
export const NEW_QUESTION_GAME = 'NEW_QUESTION_GAME';
