export const TOGGLE_PLAY_OURGAME = 'TOGGLE_PLAY_OURGAME';
export const SET_QUESTIONS_OURGAME = 'SET_QUESTIONS_OURGAME';
export const SET_GAME_NUMBER_OURGAME = 'SET_GAME_NUMBER_OURGAME';
export const SET_RANDOM_GAME_NUMBER_OURGAME = 'SET_RANDOM_GAME_NUMBER_OURGAME';
export const SET_QUESTION_NUMBER_OURGAME = 'SET_QUESTION_NUMBER_OURGAME';
export const SET_STATISTIC_OURGAME = 'SET_STATISTIC_OURGAME';
export const SET_LISTEN_ANSWER_OURGAME = 'SET_LISTEN_ANSWER_OURGAME';
export const SET_KIND_OF_OURGAME = 'SET_KIND_OF_OURGAME';
